src/Web/MVC4/Areas/Backend/Controllers/LoginController.cs
using CP.NLayer.Models.Business;
using CP.NLayer.Resources.UI;
using CP.NLayer.Service.Contracts;
using CP.NLayer.Web.Mvc4.Common;
using Microsoft.Security.Application;
using System.Web.Mvc;

namespace CP.NLayer.Web.Mvc4.Areas.Backend.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUserService _userService;

        public LoginController(IUserService userService)
        {
            _userService = userService;
        }

        public ActionResult Index()
        {
            if (BEUtility.GetCurrentUser() != null)
            {
                return RedirectToAction("", "");
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult Index(LoginModel model, string returnUrl)
        {
            if (Request["iQapTcha"] == "" &&
                Session[SessionKeys.Captcha] != null &&
                (bool)Session[SessionKeys.Captcha] == true &&
                ModelState.IsValid
                )
            {
                var user = _userService.Login(model.UserName, model.Password);
                if (user != null && user.IsActive == true)
                {
                    if (model.RememberMe)
                    {
                        CookieHelper.Set(CookieKeys.UserId, user.Id.ToString());
                    }

                    BEUtility.Login(user);

                    returnUrl = Sanitizer.GetSafeHtmlFragment(returnUrl);
                    if (Url.IsLocalUrl(returnUrl) && returnUrl.Length > 1
                        && !returnUrl.StartsWith("//") && !returnUrl.StartsWith("/\\"))
                    {
                        return Redirect(returnUrl);
                    }
                    else
                    {
                        return RedirectToAction("", "");
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, UiResources.Error_UserNameOrPasswordIncorrect);
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }
    }
}

src/Web/MVC4/Controllers/CommonController.cs
using CP.NLayer.Web.Mvc4.Common;
using System.Web.Mvc;

namespace CP.NLayer.Web.Mvc4.Controllers
{
    public class CommonController : Controller
    {
        [HttpPost]
        public ActionResult ValidateCaptcha(string action)
        {
            if (action == "qaptcha")
            {
                Session[SessionKeys.Captcha] = true;
                return Json(new { error = false });
            }
            else
            {
                Session[SessionKeys.Captcha] = null;
                return Json(new { error = true });
            }
        }
    }
}

src/Web/MVC4/Controllers/LanguageController.cs
using CP.NLayer.Web.Mvc4.Common;
using System.Linq;
using System.Web.Mvc;

namespace CP.NLayer.Web.Mvc4.Controllers
{
    public class LanguageController : Controller
    {
        [ChildActionOnly]
        public ActionResult Index()
        {
            var items = CultureHelper.DefaultSupportedCultures.Select(i => new SelectListItem
            {
                Text = i.NativeName,
                Value = i.Name,
                Selected = (i.Name == System.Threading.Thread.CurrentThread.CurrentUICulture.Name)
            });

            return PartialView(items);
        }

        [HttpPost]
        public ActionResult Change(string lang)
        {
            CookieHelper.Set(CookieKeys.UICulture, CultureHelper.GetSupportedCulture(lang, CultureHelper.DefaultSupportedCultures).Name, 3600);
            return new EmptyResult();
        }
    }
}

src/Web/MVC4/Areas/Backend/Views/Login/Index.cshtml
@model LoginModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    @Html.Partial("_BECss")
    @Html.Partial("_BEScripts")
    <link href="@Url.Content("~/Scripts/Qaptcha-v2.6/QapTcha.jquery.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/Qaptcha-v2.6/jquery.ui.touch.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Qaptcha-v2.6/QapTcha.jquery.js")" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            $('#QapTcha').QapTcha({
                PHPfile: '@Url.Action("ValidateCaptcha", "Common", new { area = "" })',
                txtLock: "@Html.Raw(UiResources.Info_CaptchaTipsBeforeValidation)",
                txtUnlock: "@UiResources.Info_CaptchaTipsAfterValidation"
            });
        })
    </script>
</head>
<body>
    <div class="container">
        @Html.Action("Index", "Language", new { area = "" })
        <div id="Login">
            @using (Html.BeginForm())
            {
                <fieldset>
                    <legend>@UiResources.Login</legend>
                    <div class="prepend-1 span-6">
                        <h1>Welcome!</h1>
                    </div>
                    <div class="span-14 colborder-left last">
                        <div class="append-bottom">
                            @Html.ValidationSummary(true)
                        </div>
                        <div>
                            @Html.LabelFor(m => m.UserName)
                            (User1)
                        </div>
                        <div class="append-bottom">
                            @Html.TextBoxFor(m => m.UserName, new { @class = "text" })
                            @Html.ValidationMessageFor(m => m.UserName)
                        </div>
                        <div>
                            @Html.LabelFor(m => m.Password)
                            (a)
                        </div>
                        <div>
                            @Html.PasswordFor(m => m.Password, new { @class = "text" })
                            @Html.ValidationMessageFor(m => m.Password)
                        </div>
                        <div id="QapTcha"></div>
                        <div>
                            <input type="submit" class="button" value="@UiResources.Login" />
                            @Html.CheckBoxFor(m => m.RememberMe, new { style = "margin-left:2em;" })
                            <label for="RememberMe">@UiResources.RememberMe</label>
                        </div>
                    </div>
                </fieldset>
            }
        </div>
    </div>
</body>
</html>